name: budget
channels:
  - conda-forge
dependencies:
  - python=3.11 # come back and update this periodically, but 3.14 is still pretty bleeding edge as of 2026-03-25 and isn't compatible with all jupyter extensions yet
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - gspread
  - pandas
  - sqlalchemy
  - psycopg2
  - pyyaml
  - requests
  - beautifulsoup4
  - selenium
  - lxml
  - rich
  - pydantic
  - pytest
  - python-dotenv
  - jupyterlab
  # purposefully leaving nbconda out of this list bc it's brittle when combined with modern conda-forge
  - ipykernel